### PRODUCTS SHOW

GET http://localhost:3000/products/1.json

### PRODUCTS INDEX

GET http://localhost:3000/products.json

### PRODUCTS CREATE

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Test plant2",
  "price": 20,
  "image_url": "none",
  "description": "test description"
}

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
  "name": "Test Pumpkin",
  "price": 0
}

### PRODUCTS DELETE
DELETE http://localhost:3000/products/10.json