### PRODUCTS SHOW

GET http://localhost:3000/products/1.json

### PRODUCTS INDEX

GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjgxOTMzMTV9.hTXffuD9da9HOcZxWwVt71e-h5-GonmDvSHUwBDh-EE

### PRODUCTS CREATE

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "New Plant",
  "price": 25,
  "description": "test description",
  "supplier_id": 2
}

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/17.json
Content-Type: application/json

{
  "name": "New Plant",
  "url": "https://live.staticflickr.com/7076/27570338206_ccb94fb8bf_m.jpg"
}

### PRODUCTS DELETE
DELETE http://localhost:3000/products/10.json

### USERS CREATE

POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "Hank Hill",
  "email": "hhill@example.com",
  "password": "password2",
  "password_confirmation": "password2"
}

### SESSIONS CREATE
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "hhill@example.com",
  "password": "password2"
}